ALTER TABLE "FLOW_DEFINITION"
ADD ("EXT" VARCHAR2(400) );

ALTER TABLE "FLOW_DEFINITION" RENAME COLUMN "FROM_CUSTOM" TO "FORM_CUSTOM";

ALTER TABLE "FLOW_DEFINITION" RENAME COLUMN "FROM_PATH" TO "FORM_PATH";

COMMENT ON COLUMN "FLOW_DEFINITION"."EXT" IS '业务详情 存业务表对象json字符串';

ALTER TABLE "FLOW_HIS_TASK"
ADD ("SKIP_TYPE" VARCHAR2(10) )
ADD ("FORM_CUSTOM" VARCHAR(1) DEFAULT 'N' )
ADD ("FORM_PATH" VARCHAR2(100) )
ADD ("EXT" VARCHAR2(400) );

COMMENT ON COLUMN "FLOW_HIS_TASK"."SKIP_TYPE" IS '流转类型（PASS通过 REJECT退回 NONE无动作）';

COMMENT ON COLUMN "FLOW_HIS_TASK"."FORM_CUSTOM" IS '审批表单是否自定义（Y是 N否）';

COMMENT ON COLUMN "FLOW_HIS_TASK"."FORM_PATH" IS '审批表单路径';

COMMENT ON COLUMN "FLOW_HIS_TASK"."EXT" IS '业务详情 存业务表对象json字符串';

ALTER TABLE "FLOW_INSTANCE"
MODIFY ("CREATE_BY" DEFAULT '' )
MODIFY ("DEL_FLAG" DEFAULT '0' );

ALTER TABLE "FLOW_NODE"
MODIFY ("DEL_FLAG" DEFAULT '0' )
ADD ("FORM_CUSTOM" VARCHAR(1) DEFAULT 'N' )
ADD ("FORM_PATH" VARCHAR2(100) );

COMMENT ON COLUMN "FLOW_NODE"."FORM_CUSTOM" IS '审批表单是否自定义（Y是 N否）';

COMMENT ON COLUMN "FLOW_NODE"."FORM_PATH" IS '审批表单路径';

ALTER TABLE "FLOW_SKIP"
MODIFY ("DEL_FLAG" DEFAULT '0' );

ALTER TABLE "FLOW_TASK"
ADD ("FORM_CUSTOM" VARCHAR(1) DEFAULT 'N' )
ADD ("FORM_PATH" VARCHAR2(100) );

COMMENT ON COLUMN "FLOW_TASK"."FORM_CUSTOM" IS '审批表单是否自定义（Y是 N否）';

COMMENT ON COLUMN "FLOW_TASK"."FORM_PATH" IS '审批表单路径';

ALTER TABLE "FLOW_USER"
MODIFY ("DEL_FLAG" DEFAULT '0' );