ALTER TABLE "FLOW_DEFINITION"
    ADD ("LISTENER_TYPE" VARCHAR2(100) )
    ADD ("LISTENER_PATH" VARCHAR2(500) );
comment on column FLOW_DEFINITION.LISTENER_TYPE is '监听器类型';
comment on column FLOW_DEFINITION.LISTENER_PATH is '监听器路径';