ALTER TABLE FLOW_HIS_TASK ADD (VARIABLE CLOB DEFAULT NULL);
COMMENT ON COLUMN FLOW_HIS_TASK.VARIABLE IS '任务变量';

ALTER TABLE FLOW_INSTANCE ADD (DEF_JSON CLOB DEFAULT NULL);
COMMENT ON COLUMN FLOW_INSTANCE.DEF_JSON IS '流程定义json';

ALTER TABLE FLOW_HIS_TASK
    MODIFY (TARGET_NODE_CODE VARCHAR2(200) DEFAULT NULL),
    MODIFY (TARGET_NODE_NAME VARCHAR2(200) DEFAULT NULL);
COMMENT ON COLUMN FLOW_HIS_TASK.TARGET_NODE_CODE IS '目标节点编码';
COMMENT ON COLUMN FLOW_HIS_TASK.TARGET_NODE_NAME IS '结束节点名称';

UPDATE FLOW_SKIP SET SKIP_CONDITION = REPLACE(SKIP_CONDITION, 'eq|', 'eq@@');

UPDATE FLOW_SKIP SET SKIP_CONDITION = REPLACE(SKIP_CONDITION, 'ge|', 'ge@@');

UPDATE FLOW_SKIP SET SKIP_CONDITION = REPLACE(SKIP_CONDITION, 'gt|', 'gt@@');

UPDATE FLOW_SKIP SET SKIP_CONDITION = REPLACE(SKIP_CONDITION, 'le|', 'le@@');

UPDATE FLOW_SKIP SET SKIP_CONDITION = REPLACE(SKIP_CONDITION, 'like|', 'like@@');

UPDATE FLOW_SKIP SET SKIP_CONDITION = REPLACE(SKIP_CONDITION, 'lt|', 'lt@@');

UPDATE FLOW_SKIP SET SKIP_CONDITION = REPLACE(SKIP_CONDITION, 'ne|', 'ne@@');

UPDATE FLOW_SKIP SET SKIP_CONDITION = REPLACE(SKIP_CONDITION, 'notNike|', 'notNike@@');

UPDATE FLOW_SKIP SET SKIP_CONDITION = REPLACE(SKIP_CONDITION, 'spel|', 'spel@@');
