#!/usr/bin/env python3
"""Generate a PostgreSQL bootstrap script for the full RuoYi + Warm-Flow Jimmer demo."""
from __future__ import annotations

import ast
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "sql/postgresql/ruoyi-warm-flow-jimmer-postgres.sql"
RY = ROOT / "sql/legacy-mysql/ry_20250522.sql"
WARM = ROOT / "sql/legacy-mysql/warm/warm-flow-all.sql"
WARM_FORM = ROOT / "sql/legacy-mysql/warm/v1-upgrade/warm-flow_form.sql"

TABLE_COLUMNS = {
    "sys_dept": ["dept_id", "parent_id", "ancestors", "dept_name", "order_num", "leader", "phone", "email", "status", "del_flag", "create_by", "create_time", "update_by", "update_time"],
    "sys_user": ["user_id", "dept_id", "user_name", "nick_name", "user_type", "email", "phonenumber", "sex", "avatar", "password", "status", "del_flag", "login_ip", "login_date", "pwd_update_date", "create_by", "create_time", "update_by", "update_time", "remark"],
    "sys_post": ["post_id", "post_code", "post_name", "post_sort", "status", "create_by", "create_time", "update_by", "update_time", "remark"],
    "sys_role": ["role_id", "role_name", "role_key", "role_sort", "data_scope", "menu_check_strictly", "dept_check_strictly", "status", "del_flag", "create_by", "create_time", "update_by", "update_time", "remark"],
    "sys_menu": ["menu_id", "menu_name", "parent_id", "order_num", "path", "component", "query", "route_name", "is_frame", "is_cache", "menu_type", "visible", "status", "perms", "icon", "create_by", "create_time", "update_by", "update_time", "remark"],
    "sys_user_role": ["user_id", "role_id"],
    "sys_role_menu": ["role_id", "menu_id"],
    "sys_role_dept": ["role_id", "dept_id"],
    "sys_user_post": ["user_id", "post_id"],
    "sys_dict_type": ["dict_id", "dict_name", "dict_type", "status", "create_by", "create_time", "update_by", "update_time", "remark"],
    "sys_dict_data": ["dict_code", "dict_sort", "dict_label", "dict_value", "dict_type", "css_class", "list_class", "is_default", "status", "create_by", "create_time", "update_by", "update_time", "remark"],
    "sys_config": ["config_id", "config_name", "config_key", "config_value", "config_type", "create_by", "create_time", "update_by", "update_time", "remark"],
    "sys_job": ["job_id", "job_name", "job_group", "invoke_target", "cron_expression", "misfire_policy", "concurrent", "status", "create_by", "create_time", "update_by", "update_time", "remark"],
    "sys_notice": ["notice_id", "notice_title", "notice_type", "notice_content", "status", "create_by", "create_time", "update_by", "update_time", "remark"],
}
RELATION_ID = {
    "sys_user_role": "user_role_id",
    "sys_role_menu": "role_menu_id",
    "sys_role_dept": "role_dept_id",
    "sys_user_post": "user_post_id",
}
FULL_COLUMNS = {
    **TABLE_COLUMNS,
    "sys_user_role": ["user_role_id", "user_id", "role_id"],
    "sys_role_menu": ["role_menu_id", "role_id", "menu_id"],
    "sys_role_dept": ["role_dept_id", "role_id", "dept_id"],
    "sys_user_post": ["user_post_id", "user_id", "post_id"],
}

SCHEMA = r"""
-- ============================================================
-- Full RuoYi Admin + Warm-Flow bootstrap for Jimmer ORM/PostgreSQL
-- Generated by scripts/generate_pg_init.py
-- Default login: admin / admin123
-- Safety: this script creates a fresh demo schema. It refuses to run against
-- a non-empty public schema unless explicitly invoked with:
--   -v allow_destructive_reset=true
-- ============================================================

\if :{?allow_destructive_reset}
\else
\set allow_destructive_reset false
\endif
\set ON_ERROR_STOP on

SELECT
  count(*) AS existing_public_table_count,
  CASE
    WHEN count(*) > 0
     AND lower(:'allow_destructive_reset') NOT IN ('1', 'true', 'yes', 'on')
    THEN 'true'
    ELSE 'false'
  END AS refuse_destructive_bootstrap
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_type = 'BASE TABLE'
\gset

\if :refuse_destructive_bootstrap
\echo 'ERROR: refusing to run destructive bootstrap against non-empty public schema.'
\echo 'DETAIL: public schema contains' :existing_public_table_count 'table(s).'
\echo 'HINT: run this against an empty database, or pass -v allow_destructive_reset=true only after backup/review.'
SELECT 1 / 0 AS destructive_bootstrap_refused;
\endif

BEGIN;

DROP TABLE IF EXISTS flow_user CASCADE;
DROP TABLE IF EXISTS flow_his_task CASCADE;
DROP TABLE IF EXISTS flow_task CASCADE;
DROP TABLE IF EXISTS flow_instance CASCADE;
DROP TABLE IF EXISTS flow_skip CASCADE;
DROP TABLE IF EXISTS flow_node CASCADE;
DROP TABLE IF EXISTS flow_definition CASCADE;
DROP TABLE IF EXISTS flow_form CASCADE;
DROP TABLE IF EXISTS test_leave CASCADE;
DROP TABLE IF EXISTS contract_process CASCADE;
DROP TABLE IF EXISTS procurement_steps CASCADE;
DROP TABLE IF EXISTS gen_table_column CASCADE;
DROP TABLE IF EXISTS gen_table CASCADE;
DROP TABLE IF EXISTS sys_notice CASCADE;
DROP TABLE IF EXISTS sys_job_log CASCADE;
DROP TABLE IF EXISTS sys_job CASCADE;
DROP TABLE IF EXISTS sys_logininfor CASCADE;
DROP TABLE IF EXISTS sys_config CASCADE;
DROP TABLE IF EXISTS sys_dict_data CASCADE;
DROP TABLE IF EXISTS sys_dict_type CASCADE;
DROP TABLE IF EXISTS sys_oper_log CASCADE;
DROP TABLE IF EXISTS sys_user_post CASCADE;
DROP TABLE IF EXISTS sys_role_dept CASCADE;
DROP TABLE IF EXISTS sys_role_menu CASCADE;
DROP TABLE IF EXISTS sys_user_role CASCADE;
DROP TABLE IF EXISTS sys_menu CASCADE;
DROP TABLE IF EXISTS sys_role CASCADE;
DROP TABLE IF EXISTS sys_post CASCADE;
DROP TABLE IF EXISTS sys_user CASCADE;
DROP TABLE IF EXISTS sys_dept CASCADE;
DROP TABLE IF EXISTS QRTZ_SIMPROP_TRIGGERS CASCADE;
DROP TABLE IF EXISTS QRTZ_LOCKS CASCADE;
DROP TABLE IF EXISTS QRTZ_SCHEDULER_STATE CASCADE;
DROP TABLE IF EXISTS QRTZ_FIRED_TRIGGERS CASCADE;
DROP TABLE IF EXISTS QRTZ_PAUSED_TRIGGER_GRPS CASCADE;
DROP TABLE IF EXISTS QRTZ_CALENDARS CASCADE;
DROP TABLE IF EXISTS QRTZ_BLOB_TRIGGERS CASCADE;
DROP TABLE IF EXISTS QRTZ_CRON_TRIGGERS CASCADE;
DROP TABLE IF EXISTS QRTZ_SIMPLE_TRIGGERS CASCADE;
DROP TABLE IF EXISTS QRTZ_TRIGGERS CASCADE;
DROP TABLE IF EXISTS QRTZ_JOB_DETAILS CASCADE;

CREATE TABLE sys_dept (
  dept_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id bigint DEFAULT 0,
  ancestors varchar(50) DEFAULT '',
  dept_name varchar(30) DEFAULT '',
  order_num int DEFAULT 0,
  leader varchar(20),
  phone varchar(11),
  email varchar(50),
  status char(1) DEFAULT '0',
  del_flag char(1) DEFAULT '0',
  create_by varchar(64) DEFAULT '',
  create_time timestamp,
  update_by varchar(64) DEFAULT '',
  update_time timestamp
);

CREATE TABLE sys_user (
  user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dept_id bigint,
  user_name varchar(30) NOT NULL,
  nick_name varchar(30) NOT NULL,
  user_type varchar(2) DEFAULT '00',
  email varchar(50) DEFAULT '',
  phonenumber varchar(11) DEFAULT '',
  sex char(1) DEFAULT '0',
  avatar varchar(100) DEFAULT '',
  password varchar(100) DEFAULT '',
  status char(1) DEFAULT '0',
  del_flag char(1) DEFAULT '0',
  login_ip varchar(128) DEFAULT '',
  login_date timestamp,
  pwd_update_date timestamp,
  create_by varchar(64) DEFAULT '',
  create_time timestamp,
  update_by varchar(64) DEFAULT '',
  update_time timestamp,
  remark varchar(500)
);
CREATE INDEX idx_sys_user_user_name ON sys_user(user_name);
CREATE INDEX idx_sys_user_dept_id ON sys_user(dept_id);

CREATE TABLE sys_post (
  post_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_code varchar(64) NOT NULL,
  post_name varchar(50) NOT NULL,
  post_sort int,
  status char(1) NOT NULL,
  create_by varchar(64) DEFAULT '',
  create_time timestamp,
  update_by varchar(64) DEFAULT '',
  update_time timestamp,
  remark varchar(500)
);

CREATE TABLE sys_role (
  role_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_name varchar(30) NOT NULL,
  role_key varchar(100) NOT NULL,
  role_sort int,
  data_scope char(1) DEFAULT '1',
  menu_check_strictly boolean DEFAULT true,
  dept_check_strictly boolean DEFAULT true,
  status char(1) NOT NULL,
  del_flag char(1) DEFAULT '0',
  create_by varchar(64) DEFAULT '',
  create_time timestamp,
  update_by varchar(64) DEFAULT '',
  update_time timestamp,
  remark varchar(500)
);

CREATE TABLE sys_menu (
  menu_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  menu_name varchar(50) NOT NULL,
  parent_id bigint DEFAULT 0,
  order_num int DEFAULT 0,
  path varchar(200) DEFAULT '',
  component varchar(255),
  query varchar(255),
  route_name varchar(50) DEFAULT '',
  is_frame varchar(1) DEFAULT '1',
  is_cache varchar(1) DEFAULT '0',
  menu_type char(1) DEFAULT '',
  visible char(1) DEFAULT '0',
  status char(1) DEFAULT '0',
  perms varchar(100),
  icon varchar(100) DEFAULT '#',
  create_by varchar(64) DEFAULT '',
  create_time timestamp,
  update_by varchar(64) DEFAULT '',
  update_time timestamp,
  remark varchar(500) DEFAULT ''
);
CREATE INDEX idx_sys_menu_parent_id ON sys_menu(parent_id);

CREATE TABLE sys_user_role (
  user_role_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  role_id bigint NOT NULL,
  UNIQUE (user_id, role_id)
);

CREATE TABLE sys_role_menu (
  role_menu_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id bigint NOT NULL,
  menu_id bigint NOT NULL,
  UNIQUE (role_id, menu_id)
);

CREATE TABLE sys_role_dept (
  role_dept_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id bigint NOT NULL,
  dept_id bigint NOT NULL,
  UNIQUE (role_id, dept_id)
);

CREATE TABLE sys_user_post (
  user_post_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  post_id bigint NOT NULL,
  UNIQUE (user_id, post_id)
);

CREATE TABLE sys_oper_log (
  oper_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(50) DEFAULT '',
  business_type int DEFAULT 0,
  method varchar(200) DEFAULT '',
  request_method varchar(10) DEFAULT '',
  operator_type int DEFAULT 0,
  oper_name varchar(50) DEFAULT '',
  dept_name varchar(50) DEFAULT '',
  oper_url varchar(255) DEFAULT '',
  oper_ip varchar(128) DEFAULT '',
  oper_location varchar(255) DEFAULT '',
  oper_param text,
  json_result text,
  status int DEFAULT 0,
  error_msg text,
  oper_time timestamp,
  cost_time bigint DEFAULT 0
);
CREATE INDEX idx_sys_oper_log_bt ON sys_oper_log(business_type);
CREATE INDEX idx_sys_oper_log_s ON sys_oper_log(status);
CREATE INDEX idx_sys_oper_log_ot ON sys_oper_log(oper_time);

CREATE TABLE sys_dict_type (
  dict_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dict_name varchar(100) NOT NULL DEFAULT '',
  dict_type varchar(100) NOT NULL DEFAULT '',
  status char(1) DEFAULT '0',
  create_by varchar(64) DEFAULT '',
  create_time timestamp,
  update_by varchar(64) DEFAULT '',
  update_time timestamp,
  remark varchar(500),
  UNIQUE (dict_type)
);

CREATE TABLE sys_dict_data (
  dict_code bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dict_sort bigint DEFAULT 0,
  dict_label varchar(100) NOT NULL DEFAULT '',
  dict_value varchar(100) NOT NULL DEFAULT '',
  dict_type varchar(100) NOT NULL DEFAULT '',
  css_class varchar(100),
  list_class varchar(100),
  is_default char(1) DEFAULT 'N',
  status char(1) DEFAULT '0',
  create_by varchar(64) DEFAULT '',
  create_time timestamp,
  update_by varchar(64) DEFAULT '',
  update_time timestamp,
  remark varchar(500)
);

CREATE TABLE sys_config (
  config_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  config_name varchar(100) NOT NULL DEFAULT '',
  config_key varchar(100) NOT NULL DEFAULT '',
  config_value varchar(500) NOT NULL DEFAULT '',
  config_type char(1) DEFAULT 'N',
  create_by varchar(64) DEFAULT '',
  create_time timestamp,
  update_by varchar(64) DEFAULT '',
  update_time timestamp,
  remark varchar(500)
);

CREATE TABLE sys_logininfor (
  info_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name varchar(50) DEFAULT '',
  status char(1) DEFAULT '0',
  ipaddr varchar(128) DEFAULT '',
  login_location varchar(255) DEFAULT '',
  browser varchar(50) DEFAULT '',
  os varchar(50) DEFAULT '',
  msg varchar(255) DEFAULT '',
  login_time timestamp
);
CREATE INDEX idx_sys_logininfor_s ON sys_logininfor(status);
CREATE INDEX idx_sys_logininfor_lt ON sys_logininfor(login_time);

CREATE TABLE sys_job (
  job_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_name varchar(64) NOT NULL DEFAULT '',
  job_group varchar(64) NOT NULL DEFAULT 'DEFAULT',
  invoke_target varchar(500) NOT NULL,
  cron_expression varchar(255) DEFAULT '',
  misfire_policy varchar(20) DEFAULT '3',
  concurrent char(1) DEFAULT '1',
  status char(1) DEFAULT '0',
  create_by varchar(64) DEFAULT '',
  create_time timestamp,
  update_by varchar(64) DEFAULT '',
  update_time timestamp,
  remark varchar(500) DEFAULT ''
);
CREATE UNIQUE INDEX uk_sys_job_name_group ON sys_job(job_id, job_name, job_group);

CREATE TABLE sys_job_log (
  job_log_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_name varchar(64) NOT NULL,
  job_group varchar(64) NOT NULL,
  invoke_target varchar(500) NOT NULL,
  job_message varchar(500),
  status char(1) DEFAULT '0',
  exception_info text DEFAULT '',
  create_time timestamp,
  start_time timestamp,
  stop_time timestamp
);

CREATE TABLE sys_notice (
  notice_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notice_title varchar(50) NOT NULL,
  notice_type char(1) NOT NULL,
  notice_content text,
  status char(1) DEFAULT '0',
  create_by varchar(64) DEFAULT '',
  create_time timestamp,
  update_by varchar(64) DEFAULT '',
  update_time timestamp,
  remark varchar(255)
);

CREATE TABLE gen_table (
  table_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name varchar(200) NOT NULL DEFAULT '',
  table_comment varchar(500) NOT NULL DEFAULT '',
  sub_table_name varchar(64),
  sub_table_fk_name varchar(64),
  class_name varchar(100) NOT NULL DEFAULT '',
  tpl_category varchar(200) DEFAULT 'crud',
  tpl_web_type varchar(30) DEFAULT '',
  package_name varchar(100),
  module_name varchar(30),
  business_name varchar(30),
  function_name varchar(50),
  function_author varchar(50),
  gen_type char(1) DEFAULT '0',
  gen_path varchar(200) DEFAULT '/',
  options varchar(1000),
  create_by varchar(64) DEFAULT '',
  create_time timestamp,
  update_by varchar(64) DEFAULT '',
  update_time timestamp,
  remark varchar(500)
);

CREATE TABLE gen_table_column (
  column_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_id bigint NOT NULL,
  column_name varchar(200) NOT NULL,
  column_comment varchar(500),
  column_type varchar(100) NOT NULL,
  java_type varchar(500),
  java_field varchar(200),
  is_pk char(1),
  is_increment char(1),
  is_required char(1),
  is_insert char(1),
  is_edit char(1),
  is_list char(1),
  is_query char(1),
  query_type varchar(200) DEFAULT 'EQ',
  html_type varchar(200),
  dict_type varchar(200) DEFAULT '',
  sort int,
  create_by varchar(64) DEFAULT '',
  create_time timestamp,
  update_by varchar(64) DEFAULT '',
  update_time timestamp
);

CREATE TABLE flow_definition (
  id bigint PRIMARY KEY,
  flow_code varchar(40),
  flow_name varchar(100),
  model_value varchar(40) DEFAULT 'CLASSICS',
  category varchar(100),
  "version" varchar(20),
  is_publish smallint DEFAULT 0,
  form_custom char(1) DEFAULT 'N',
  form_path varchar(100),
  activity_status smallint DEFAULT 1,
  listener_type varchar(100),
  listener_path varchar(400),
  ext varchar(500),
  create_time timestamp,
  create_by varchar(64) DEFAULT '',
  update_time timestamp,
  update_by varchar(64) DEFAULT '',
  del_flag char(1) DEFAULT '0',
  tenant_id varchar(40)
);

CREATE TABLE flow_form (
  id bigint PRIMARY KEY,
  form_code varchar(40),
  form_name varchar(100),
  "version" varchar(20),
  is_publish smallint DEFAULT 0,
  form_type smallint DEFAULT 0,
  form_path varchar(100),
  form_content text,
  ext varchar(400),
  create_time timestamp,
  create_by varchar(64) DEFAULT '',
  update_time timestamp,
  update_by varchar(64) DEFAULT '',
  del_flag char(1) DEFAULT '0',
  tenant_id varchar(40)
);

CREATE TABLE flow_node (
  id bigint PRIMARY KEY,
  node_type smallint,
  definition_id bigint,
  node_code varchar(100),
  node_name varchar(100),
  permission_flag varchar(200),
  node_ratio varchar(200),
  coordinate varchar(100),
  any_node_skip varchar(100),
  listener_type varchar(100),
  listener_path varchar(400),
  form_custom char(1) DEFAULT 'N',
  form_path varchar(100),
  "version" varchar(20),
  create_time timestamp,
  create_by varchar(64) DEFAULT '',
  update_time timestamp,
  update_by varchar(64) DEFAULT '',
  ext text,
  del_flag char(1) DEFAULT '0',
  tenant_id varchar(40)
);

CREATE TABLE flow_skip (
  id bigint PRIMARY KEY,
  definition_id bigint,
  node_id bigint NULL,
  now_node_code varchar(100),
  now_node_type smallint,
  next_node_code varchar(100),
  next_node_type smallint,
  skip_name varchar(100),
  skip_type varchar(40),
  skip_condition varchar(200),
  coordinate varchar(100),
  create_time timestamp,
  create_by varchar(64) DEFAULT '',
  update_time timestamp,
  update_by varchar(64) DEFAULT '',
  del_flag char(1) DEFAULT '0',
  tenant_id varchar(40)
);

CREATE TABLE flow_instance (
  id bigint PRIMARY KEY,
  definition_id bigint,
  business_id varchar(40),
  node_type smallint,
  node_code varchar(40),
  node_name varchar(100),
  variable text,
  flow_status varchar(20),
  activity_status smallint DEFAULT 1,
  form_custom char(1) DEFAULT 'N',
  form_path varchar(100),
  def_json text,
  create_time timestamp,
  create_by varchar(64) DEFAULT '',
  update_time timestamp,
  update_by varchar(64) DEFAULT '',
  ext varchar(500),
  del_flag char(1) DEFAULT '0',
  tenant_id varchar(40)
);

CREATE TABLE flow_task (
  id bigint PRIMARY KEY,
  definition_id bigint,
  instance_id bigint,
  node_code varchar(100),
  node_name varchar(100),
  node_type smallint,
  flow_status varchar(20),
  form_custom char(1) DEFAULT 'N',
  form_path varchar(100),
  create_time timestamp,
  create_by varchar(64) DEFAULT '',
  update_time timestamp,
  update_by varchar(64) DEFAULT '',
  del_flag char(1) DEFAULT '0',
  tenant_id varchar(40)
);

CREATE TABLE flow_his_task (
  id bigint PRIMARY KEY,
  definition_id bigint,
  instance_id bigint,
  task_id bigint,
  node_code varchar(100),
  node_name varchar(100),
  node_type smallint,
  target_node_code varchar(200),
  target_node_name varchar(200),
  approver varchar(40),
  cooperate_type smallint DEFAULT 0,
  collaborator varchar(500),
  skip_type varchar(10),
  flow_status varchar(20),
  form_custom char(1) DEFAULT 'N',
  form_path varchar(100),
  ext text,
  message varchar(500),
  variable text,
  create_time timestamp,
  update_time timestamp,
  del_flag char(1) DEFAULT '0',
  tenant_id varchar(40)
);

CREATE TABLE flow_user (
  id bigint PRIMARY KEY,
  "type" char(1),
  processed_by varchar(80),
  associated bigint,
  create_time timestamp,
  create_by varchar(64) DEFAULT '',
  update_time timestamp,
  update_by varchar(64) DEFAULT '',
  del_flag char(1) DEFAULT '0',
  tenant_id varchar(40)
);
CREATE INDEX user_processed_type ON flow_user(processed_by, "type");
CREATE INDEX user_associated_idx ON flow_user(associated);

CREATE TABLE test_leave (
  id varchar(40) PRIMARY KEY,
  "type" bigint,
  reason varchar(500),
  start_time timestamp,
  end_time timestamp,
  day bigint,
  instance_id bigint,
  node_code varchar(100),
  node_name varchar(100),
  node_type int,
  flow_status varchar(20),
  del_flag char(1) DEFAULT '0',
  create_by varchar(64) DEFAULT '',
  create_time timestamp DEFAULT CURRENT_TIMESTAMP,
  update_by varchar(64) DEFAULT '',
  update_time timestamp DEFAULT CURRENT_TIMESTAMP,
  remark varchar(500)
);

CREATE TABLE contract_process (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contract_name varchar(255),
  contract_type varchar(100),
  structure_and_nature text,
  proposed_conditions text,
  negotiation_content text,
  file_id varchar(500),
  negotiation_result text,
  adjustment_scheme text,
  sign_date timestamp,
  signer varchar(255),
  filing_date timestamp,
  filing_department varchar(255),
  instance_id bigint,
  node_code varchar(100),
  node_name varchar(100),
  node_type int,
  flow_status varchar(20),
  del_flag char(1) DEFAULT '0',
  create_by varchar(64) DEFAULT '',
  create_time timestamp DEFAULT CURRENT_TIMESTAMP,
  update_by varchar(64) DEFAULT '',
  update_time timestamp DEFAULT CURRENT_TIMESTAMP,
  remark varchar(500)
);

CREATE TABLE procurement_steps (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_name varchar(255),
  purchase_plan varchar(2000),
  urgent char(1),
  urgent_purchase_plan varchar(2000),
  on_demand_procurement varchar(255),
  provide_items varchar(255),
  product_inspection char(1),
  issue_invoice varchar(255),
  record_entry varchar(2000),
  return_items varchar(255),
  warehousing varchar(255),
  receive_items varchar(255),
  maintain_records varchar(2000),
  instance_id bigint,
  node_code varchar(100),
  node_name varchar(100),
  node_type int,
  flow_status varchar(20),
  del_flag char(1) DEFAULT '0',
  create_by varchar(64) DEFAULT '',
  create_time timestamp DEFAULT CURRENT_TIMESTAMP,
  update_by varchar(64) DEFAULT '',
  update_time timestamp DEFAULT CURRENT_TIMESTAMP,
  remark varchar(500)
);
"""

QUARTZ = r"""
-- Quartz tables
CREATE TABLE QRTZ_JOB_DETAILS (
    sched_name varchar(120) NOT NULL,
    job_name varchar(200) NOT NULL,
    job_group varchar(200) NOT NULL,
    description varchar(250),
    job_class_name varchar(250) NOT NULL,
    is_durable varchar(1) NOT NULL,
    is_nonconcurrent varchar(1) NOT NULL,
    is_update_data varchar(1) NOT NULL,
    requests_recovery varchar(1) NOT NULL,
    job_data bytea,
    PRIMARY KEY (sched_name, job_name, job_group)
);
CREATE TABLE QRTZ_TRIGGERS (
    sched_name varchar(120) NOT NULL,
    trigger_name varchar(200) NOT NULL,
    trigger_group varchar(200) NOT NULL,
    job_name varchar(200) NOT NULL,
    job_group varchar(200) NOT NULL,
    description varchar(250),
    next_fire_time bigint,
    prev_fire_time bigint,
    priority integer,
    trigger_state varchar(16) NOT NULL,
    trigger_type varchar(8) NOT NULL,
    start_time bigint NOT NULL,
    end_time bigint,
    calendar_name varchar(200),
    misfire_instr smallint,
    job_data bytea,
    PRIMARY KEY (sched_name, trigger_name, trigger_group),
    FOREIGN KEY (sched_name, job_name, job_group) REFERENCES QRTZ_JOB_DETAILS(sched_name, job_name, job_group)
);
CREATE TABLE QRTZ_SIMPLE_TRIGGERS (
    sched_name varchar(120) NOT NULL,
    trigger_name varchar(200) NOT NULL,
    trigger_group varchar(200) NOT NULL,
    repeat_count bigint NOT NULL,
    repeat_interval bigint NOT NULL,
    times_triggered bigint NOT NULL,
    PRIMARY KEY (sched_name, trigger_name, trigger_group),
    FOREIGN KEY (sched_name, trigger_name, trigger_group) REFERENCES QRTZ_TRIGGERS(sched_name, trigger_name, trigger_group)
);
CREATE TABLE QRTZ_CRON_TRIGGERS (
    sched_name varchar(120) NOT NULL,
    trigger_name varchar(200) NOT NULL,
    trigger_group varchar(200) NOT NULL,
    cron_expression varchar(200) NOT NULL,
    time_zone_id varchar(80),
    PRIMARY KEY (sched_name, trigger_name, trigger_group),
    FOREIGN KEY (sched_name, trigger_name, trigger_group) REFERENCES QRTZ_TRIGGERS(sched_name, trigger_name, trigger_group)
);
CREATE TABLE QRTZ_BLOB_TRIGGERS (
    sched_name varchar(120) NOT NULL,
    trigger_name varchar(200) NOT NULL,
    trigger_group varchar(200) NOT NULL,
    blob_data bytea,
    PRIMARY KEY (sched_name, trigger_name, trigger_group),
    FOREIGN KEY (sched_name, trigger_name, trigger_group) REFERENCES QRTZ_TRIGGERS(sched_name, trigger_name, trigger_group)
);
CREATE TABLE QRTZ_CALENDARS (
    sched_name varchar(120) NOT NULL,
    calendar_name varchar(200) NOT NULL,
    calendar bytea NOT NULL,
    PRIMARY KEY (sched_name, calendar_name)
);
CREATE TABLE QRTZ_PAUSED_TRIGGER_GRPS (
    sched_name varchar(120) NOT NULL,
    trigger_group varchar(200) NOT NULL,
    PRIMARY KEY (sched_name, trigger_group)
);
CREATE TABLE QRTZ_FIRED_TRIGGERS (
    sched_name varchar(120) NOT NULL,
    entry_id varchar(95) NOT NULL,
    trigger_name varchar(200) NOT NULL,
    trigger_group varchar(200) NOT NULL,
    instance_name varchar(200) NOT NULL,
    fired_time bigint NOT NULL,
    sched_time bigint NOT NULL,
    priority integer NOT NULL,
    state varchar(16) NOT NULL,
    job_name varchar(200),
    job_group varchar(200),
    is_nonconcurrent varchar(1),
    requests_recovery varchar(1),
    PRIMARY KEY (sched_name, entry_id)
);
CREATE TABLE QRTZ_SCHEDULER_STATE (
    sched_name varchar(120) NOT NULL,
    instance_name varchar(200) NOT NULL,
    last_checkin_time bigint NOT NULL,
    checkin_interval bigint NOT NULL,
    PRIMARY KEY (sched_name, instance_name)
);
CREATE TABLE QRTZ_LOCKS (
    sched_name varchar(120) NOT NULL,
    lock_name varchar(40) NOT NULL,
    PRIMARY KEY (sched_name, lock_name)
);
CREATE TABLE QRTZ_SIMPROP_TRIGGERS (
    sched_name varchar(120) NOT NULL,
    trigger_name varchar(200) NOT NULL,
    trigger_group varchar(200) NOT NULL,
    str_prop_1 varchar(512),
    str_prop_2 varchar(512),
    str_prop_3 varchar(512),
    int_prop_1 integer,
    int_prop_2 integer,
    long_prop_1 bigint,
    long_prop_2 bigint,
    dec_prop_1 numeric(13,4),
    dec_prop_2 numeric(13,4),
    bool_prop_1 varchar(1),
    bool_prop_2 varchar(1),
    PRIMARY KEY (sched_name, trigger_name, trigger_group),
    FOREIGN KEY (sched_name, trigger_name, trigger_group) REFERENCES QRTZ_TRIGGERS(sched_name, trigger_name, trigger_group)
);
"""

TAIL = r"""
-- Keep identity sequences ahead of explicit bootstrap ids.
SELECT setval(pg_get_serial_sequence('sys_dept','dept_id'), COALESCE((SELECT max(dept_id) FROM sys_dept), 1), true);
SELECT setval(pg_get_serial_sequence('sys_user','user_id'), COALESCE((SELECT max(user_id) FROM sys_user), 1), true);
SELECT setval(pg_get_serial_sequence('sys_post','post_id'), COALESCE((SELECT max(post_id) FROM sys_post), 1), true);
SELECT setval(pg_get_serial_sequence('sys_role','role_id'), COALESCE((SELECT max(role_id) FROM sys_role), 1), true);
SELECT setval(pg_get_serial_sequence('sys_menu','menu_id'), COALESCE((SELECT max(menu_id) FROM sys_menu), 1), true);
SELECT setval(pg_get_serial_sequence('sys_user_role','user_role_id'), COALESCE((SELECT max(user_role_id) FROM sys_user_role), 1), true);
SELECT setval(pg_get_serial_sequence('sys_role_menu','role_menu_id'), COALESCE((SELECT max(role_menu_id) FROM sys_role_menu), 1), true);
SELECT setval(pg_get_serial_sequence('sys_role_dept','role_dept_id'), COALESCE((SELECT max(role_dept_id) FROM sys_role_dept), 1), true);
SELECT setval(pg_get_serial_sequence('sys_user_post','user_post_id'), COALESCE((SELECT max(user_post_id) FROM sys_user_post), 1), true);
SELECT setval(pg_get_serial_sequence('sys_oper_log','oper_id'), COALESCE((SELECT max(oper_id) FROM sys_oper_log), 1), true);
SELECT setval(pg_get_serial_sequence('sys_dict_type','dict_id'), COALESCE((SELECT max(dict_id) FROM sys_dict_type), 1), true);
SELECT setval(pg_get_serial_sequence('sys_dict_data','dict_code'), COALESCE((SELECT max(dict_code) FROM sys_dict_data), 1), true);
SELECT setval(pg_get_serial_sequence('sys_config','config_id'), COALESCE((SELECT max(config_id) FROM sys_config), 1), true);
SELECT setval(pg_get_serial_sequence('sys_logininfor','info_id'), COALESCE((SELECT max(info_id) FROM sys_logininfor), 1), true);
SELECT setval(pg_get_serial_sequence('sys_job','job_id'), COALESCE((SELECT max(job_id) FROM sys_job), 1), true);
SELECT setval(pg_get_serial_sequence('sys_job_log','job_log_id'), COALESCE((SELECT max(job_log_id) FROM sys_job_log), 1), true);
SELECT setval(pg_get_serial_sequence('sys_notice','notice_id'), COALESCE((SELECT max(notice_id) FROM sys_notice), 1), true);
SELECT setval(pg_get_serial_sequence('gen_table','table_id'), COALESCE((SELECT max(table_id) FROM gen_table), 1), true);
SELECT setval(pg_get_serial_sequence('gen_table_column','column_id'), COALESCE((SELECT max(column_id) FROM gen_table_column), 1), true);
SELECT setval(pg_get_serial_sequence('contract_process','id'), COALESCE((SELECT max(id) FROM contract_process), 1), true);
SELECT setval(pg_get_serial_sequence('procurement_steps','id'), COALESCE((SELECT max(id) FROM procurement_steps), 1), true);

-- Grant the runtime user access to the bootstrap schema objects.
GRANT USAGE, CREATE ON SCHEMA public TO CURRENT_USER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO CURRENT_USER;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO CURRENT_USER;

COMMIT;
"""

INSERT_RE = re.compile(r"insert\s+into\s+`?(\w+)`?\s*(?:\((.*?)\))?\s*values\s*", re.I | re.S)


def extract_insert_statements(text: str, tables: set[str]) -> list[tuple[str, list[str] | None, str]]:
    rows = []
    pos = 0
    while True:
        m = INSERT_RE.search(text, pos)
        if not m:
            break
        table = m.group(1)
        start = m.end()
        i = start
        in_str = False
        while i < len(text):
            ch = text[i]
            if ch == "'":
                if in_str and i + 1 < len(text) and text[i + 1] == "'":
                    i += 2
                    continue
                if in_str and i > 0 and text[i - 1] == "\\":
                    i += 1
                    continue
                in_str = not in_str
            elif ch == ";" and not in_str:
                break
            i += 1
        values = text[start:i].strip()
        pos = i + 1
        if table.lower() in tables:
            cols = None
            if m.group(2):
                cols = [c.strip().strip('`').lower() for c in m.group(2).split(',')]
            rows.append((table.lower(), cols, values))
    return rows


def split_tuple_values(values: str) -> list[str]:
    values = values.strip()
    # bootstrap data uses one tuple per insert; keep defensive parsing for comma-separated tuples.
    tuples = []
    depth = 0
    start = None
    in_str = False
    i = 0
    while i < len(values):
        ch = values[i]
        if ch == "'":
            if in_str and i + 1 < len(values) and values[i + 1] == "'":
                i += 2
                continue
            if in_str and i > 0 and values[i - 1] == "\\":
                i += 1
                continue
            in_str = not in_str
        elif not in_str:
            if ch == '(':
                if depth == 0:
                    start = i
                depth += 1
            elif ch == ')':
                depth -= 1
                if depth == 0 and start is not None:
                    tuples.append(values[start:i+1])
                    start = None
        i += 1
    return tuples or [values]


def convert_expr(expr: str) -> str:
    s = expr.strip()
    if not s:
        return s
    lower = s.lower()
    if lower == "sysdate()":
        return "now()"
    if lower == "current_timestamp()":
        return "CURRENT_TIMESTAMP"
    if lower == "null":
        return "NULL"
    # MySQL escaped strings: \' appears in cron invoke targets.
    if s.startswith("'") and s.endswith("'"):
        body = s[1:-1].replace("\\'", "''")
        return "'" + body + "'"
    return s.replace("`", "")


def parse_tuple(tuple_sql: str) -> list[str]:
    inner = tuple_sql.strip()[1:-1]
    vals = []
    buf = []
    in_str = False
    depth = 0
    i = 0
    while i < len(inner):
        ch = inner[i]
        if ch == "'":
            buf.append(ch)
            if in_str and i + 1 < len(inner) and inner[i + 1] == "'":
                buf.append(inner[i + 1])
                i += 2
                continue
            if in_str and i > 0 and inner[i - 1] == "\\":
                i += 1
                continue
            in_str = not in_str
        elif ch == '(' and not in_str:
            depth += 1
            buf.append(ch)
        elif ch == ')' and not in_str:
            depth -= 1
            buf.append(ch)
        elif ch == ',' and not in_str and depth == 0:
            vals.append(convert_expr(''.join(buf).strip()))
            buf = []
        else:
            buf.append(ch)
        i += 1
    vals.append(convert_expr(''.join(buf).strip()))
    return vals


def boolize(value: str) -> str:
    raw = value.strip().strip("'").lower()
    return "true" if raw in {"1", "true", "t", "y"} else "false"


def normalize_insert(table: str, cols: list[str] | None, tuple_sql: str) -> str | None:
    vals = parse_tuple(tuple_sql)
    if cols is None:
        cols = TABLE_COLUMNS.get(table)
        if cols is None:
            return None
    # Old Warm-Flow menu inserts pre-date route_name; fill it.
    if table == "sys_menu" and "route_name" not in cols:
        qpos = cols.index("query")
        cols = cols[:qpos+1] + ["route_name"] + cols[qpos+1:]
        vals = vals[:qpos+1] + ["''"] + vals[qpos+1:]
    if table == "sys_user" and "pwd_update_date" not in cols:
        # Warm demo user inserts omit the later RuoYi password-update column.
        login_pos = cols.index("login_date")
        cols = cols[:login_pos+1] + ["pwd_update_date"] + cols[login_pos+1:]
        vals = vals[:login_pos+1] + ["NULL"] + vals[login_pos+1:]
    if table in RELATION_ID and RELATION_ID[table] in cols:
        idx = cols.index(RELATION_ID[table])
        cols = cols[:idx] + cols[idx+1:]
        vals = vals[:idx] + vals[idx+1:]
    if len(cols) != len(vals):
        raise ValueError(f"{table}: columns {len(cols)} != values {len(vals)} for {tuple_sql[:120]}")
    converted = []
    for col, val in zip(cols, vals):
        if table == "sys_role" and col in {"menu_check_strictly", "dept_check_strictly"}:
            converted.append(boolize(val))
        elif table == "sys_menu" and col in {"is_frame", "is_cache"}:
            converted.append("'" + val.strip().strip("'") + "'")
        else:
            converted.append(val)
    qcols = [f'"{c}"' if c in {"type"} else c for c in cols]
    return f"INSERT INTO {table} ({', '.join(qcols)}) VALUES ({', '.join(converted)});"


def convert_base_inserts() -> list[str]:
    tables = {"sys_dept", "sys_user", "sys_post", "sys_role", "sys_menu", "sys_user_role", "sys_role_menu", "sys_role_dept", "sys_user_post", "sys_dict_type", "sys_dict_data", "sys_config", "sys_job", "sys_notice"}
    rows = extract_insert_statements(RY.read_text(), tables)
    out = ["\n-- RuoYi system seed data"]
    for table, cols, values in rows:
        for tup in split_tuple_values(values):
            out.append(normalize_insert(table, cols, tup))
    return out


def convert_warm_demo_inserts() -> list[str]:
    text = WARM.read_text()
    # Drop MySQL @parentId block; explicit deterministic menu ids are inserted below.
    text = re.sub(r"-- 菜单 SQL.*?CREATE TABLE `procurement_steps`", "CREATE TABLE `procurement_steps`", text, flags=re.S)
    tables = {"sys_menu", "sys_dict_type", "sys_dict_data", "sys_role", "sys_user", "sys_user_role", "sys_role_menu"}
    rows = extract_insert_statements(text, tables)
    seen = set()
    out = ["\n-- Warm-Flow menus, dictionaries, roles and demo users"]
    for table, cols, values in rows:
        for tup in split_tuple_values(values):
            stmt = normalize_insert(table, cols, tup)
            # Base script already inserts dict ids 1..10, user ids 1..2, roles 1..2, base role-menu entries.
            key = stmt
            if table in {"sys_dict_type", "sys_dict_data", "sys_user", "sys_role"}:
                # ON CONFLICT would hide real bad schema; skip only deterministic duplicates by primary key.
                pk_val = parse_tuple(tup)[0].strip().strip("'")
                key = (table, pk_val)
                if key in seen:
                    continue
                seen.add(key)
                if (table == "sys_dict_type" and pk_val in {str(i) for i in range(1, 11)}) or \
                   (table == "sys_dict_data" and pk_val in {str(i) for i in range(1, 30)}) or \
                   (table == "sys_user" and pk_val in {"1", "2"}) or \
                   (table == "sys_role" and pk_val in {"1", "2"}):
                    continue
            out.append(stmt)
    # Deterministic replacement for the MySQL LAST_INSERT_ID procurement menu block.
    out += [
        "INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2013, '企业采购', 1061, 2, 'steps', 'system/steps/index', NULL, '', '1', '0', 'C', '0', '0', 'system:steps:list', '#', 'admin', now(), '', NULL, '企业采购菜单');",
        "INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2014, '企业采购查询', 2013, 1, '#', '', NULL, '', '1', '0', 'F', '0', '0', 'system:steps:query', '#', 'admin', now(), '', NULL, '');",
        "INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2015, '企业采购新增', 2013, 2, '#', '', NULL, '', '1', '0', 'F', '0', '0', 'system:steps:add', '#', 'admin', now(), '', NULL, '');",
        "INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2016, '企业采购修改', 2013, 3, '#', '', NULL, '', '1', '0', 'F', '0', '0', 'system:steps:edit', '#', 'admin', now(), '', NULL, '');",
        "INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2017, '企业采购删除', 2013, 4, '#', '', NULL, '', '1', '0', 'F', '0', '0', 'system:steps:remove', '#', 'admin', now(), '', NULL, '');",
        "INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2018, '企业采购导出', 2013, 5, '#', '', NULL, '', '1', '0', 'F', '0', '0', 'system:steps:export', '#', 'admin', now(), '', NULL, '');",
        "INSERT INTO sys_role_menu (role_id, menu_id) VALUES (100, 2013);",
        "INSERT INTO sys_role_menu (role_id, menu_id) VALUES (100, 2014);",
        "INSERT INTO sys_role_menu (role_id, menu_id) VALUES (100, 2015);",
        "INSERT INTO sys_role_menu (role_id, menu_id) VALUES (100, 2016);",
        "INSERT INTO sys_role_menu (role_id, menu_id) VALUES (100, 2017);",
        "INSERT INTO sys_role_menu (role_id, menu_id) VALUES (100, 2018);",
        "INSERT INTO sys_role_menu (role_id, menu_id) VALUES (101, 2013);",
        "INSERT INTO sys_role_menu (role_id, menu_id) VALUES (101, 2014);",
        "INSERT INTO sys_role_menu (role_id, menu_id) VALUES (101, 2015);",
        "INSERT INTO sys_role_menu (role_id, menu_id) VALUES (101, 2016);",
        "INSERT INTO sys_role_menu (role_id, menu_id) VALUES (101, 2017);",
        "INSERT INTO sys_role_menu (role_id, menu_id) VALUES (101, 2018);",
        "INSERT INTO sys_role_menu (role_id, menu_id) VALUES (2, 1061);",
        "INSERT INTO sys_role_menu (role_id, menu_id) VALUES (2, 1092);",
        "INSERT INTO sys_role_menu (role_id, menu_id) VALUES (2, 2007);",
        "INSERT INTO sys_role_menu (role_id, menu_id) VALUES (2, 2013);",
    ]
    form_rows = extract_insert_statements(WARM_FORM.read_text(), {"sys_menu", "sys_dict_data", "flow_form"})
    for table, cols, values in form_rows:
        for tup in split_tuple_values(values):
            out.append(normalize_insert(table, cols, tup))
    return out


def sample_business_data() -> list[str]:
    return [
        "\n-- Business-flow sample rows for smoke testing list pages",
        "INSERT INTO test_leave (id, \"type\", reason, start_time, end_time, day, instance_id, node_code, node_name, node_type, flow_status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES ('leave-demo-001', 1, '年度调休示例', now(), now() + interval '2 days', 2, NULL, NULL, NULL, NULL, '0', '0', 'admin', now(), '', NULL, '初始化示例');",
        "INSERT INTO contract_process (id, contract_name, contract_type, structure_and_nature, proposed_conditions, negotiation_content, file_id, negotiation_result, adjustment_scheme, sign_date, signer, filing_date, filing_department, instance_id, node_code, node_name, node_type, flow_status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (1, '示例采购合同', '采购', '标准采购合同', '按年度框架执行', '首轮谈判完成', NULL, '待复核', NULL, NULL, NULL, NULL, '财务部', NULL, NULL, NULL, NULL, '0', '0', 'admin', now(), '', NULL, '初始化示例');",
        "INSERT INTO procurement_steps (id, purchase_name, purchase_plan, urgent, urgent_purchase_plan, on_demand_procurement, provide_items, product_inspection, issue_invoice, record_entry, return_items, warehousing, receive_items, maintain_records, instance_id, node_code, node_name, node_type, flow_status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (1, '示例办公设备采购', '采购笔记本和显示器', '1', NULL, '按需采购', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '0', 'admin', now(), '', NULL, '初始化示例');",
    ]


def main() -> None:
    parts = [SCHEMA, QUARTZ]
    parts.extend(convert_base_inserts())
    parts.extend(convert_warm_demo_inserts())
    parts.extend(sample_business_data())
    parts.append(TAIL)
    sql = "\n".join(x for x in parts if x)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(sql + "\n")
    print(OUT)
    print(f"lines={sql.count(chr(10))+1} bytes={len(sql.encode())}")

if __name__ == "__main__":
    main()
